function [] = PlotResults(t,state,env)
%% Derived Variables

% Usefull variables that rest implicit on the state variables
P_T = 1e-5*(state(:,1) + env.Motor.n_spv) .* env.R_u .* state(:,3)./ (env.Motor.V_T - state(:,2).*env.Motor.V_mol_oxl(state(:,3))); % Tank Pressure [bars]
temp = diff(state(:,11)); F = zeros(length(temp),1);
for i = 1:length(F); F(i) = temp(i)/(t(i+1)-t(i)); end % Thrust [N]

%% Plots

    figure(1)
    subplot(2,4,1), plot(t(:),state(:,3),'k'), ...
        title('Average Tank Temperature'),...
        xlabel('Time [s]'),...
        ylabel('Temperature [K]');
        set(gca, ...
            'Box'         , 'off'     , ...
            'TickDir'     , 'out'     , ...
            'XMinorTick'  , 'on'      , ...
            'YMinorTick'  , 'on'      , ...
            'YGrid'       , 'on'      , ...
            'XColor'      , [.3 .3 .3], ...
            'YColor'      , [.3 .3 .3], ...
            'LineWidth'   , 1         , ...
            'FontName'   , 'Helvetica');
    subplot(2,4,2), plot(t(:),state(:,1)*env.Motor.MW_ox,'k-o','MarkerIndices',1:ceil(length(t)/20):length(t)),
                    hold, plot(t(:),state(:,2)*env.Motor.MW_ox,'k'),hold off, ...
        title('Mass of N2O'),...
        xlabel('Time [s]'),...
        ylabel('Mass of N2O [kg]'),...
        legend('kg of N2O gas','kg of N2O liquid');
        set(gca, ...
            'Box'         , 'off'     , ...
            'TickDir'     , 'out'     , ...
            'XMinorTick'  , 'on'      , ...
            'YMinorTick'  , 'on'      , ...
            'YGrid'       , 'on'      , ...
            'XColor'      , [.3 .3 .3], ...
            'YColor'      , [.3 .3 .3], ...
            'LineWidth'   , 1         , ...
            'FontName'   , 'Helvetica');
    subplot(2,4,3), plot(t(:),state(:,4),'k'), ...
        title('Port Radius'),...
        xlabel('Time [s]'),...
        ylabel('Radius [m]');
        set(gca, ...
            'Box'         , 'off'     , ...
            'TickDir'     , 'out'     , ...
            'XMinorTick'  , 'on'      , ...
            'YMinorTick'  , 'on'      , ...
            'YGrid'       , 'on'      , ...
            'XColor'      , [.3 .3 .3], ...
            'YColor'      , [.3 .3 .3], ...
            'LineWidth'   , 1         , ...
            'FontName'   , 'Helvetica');
    subplot(2,4,4), plot(t(:),state(:,5)/1e5,'k'),...
        hold, plot(t(:),P_T,'k-s','MarkerIndices',1:ceil(length(t)/20):length(t)),hold off, ...
        title('Pressure'),...
        xlabel('Time [s]'),...
        ylabel('Pressure [Bars]');
        legend('Chamber', 'Oxidizer Tank');
         set(gca, ...
            'Box'         , 'off'     , ...
            'TickDir'     , 'out'     , ...
            'XMinorTick'  , 'on'      , ...
            'YMinorTick'  , 'on'      , ...
            'YGrid'       , 'on'      , ...
            'XColor'      , [.3 .3 .3], ...
            'YColor'      , [.3 .3 .3], ...
            'LineWidth'   , 1         , ...
            'FontName'   , 'Helvetica');
    subplot(2,4,5), plot(t(:),state(:,7),'k'),grid, ...
        title('Chamber Gas Density'),...
        xlabel('Time [s]'),...
        ylabel('Density [kg/m^3]');
         set(gca, ...
            'Box'         , 'off'     , ...
            'TickDir'     , 'out'     , ...
            'XMinorTick'  , 'on'      , ...
            'YMinorTick'  , 'on'      , ...
            'YGrid'       , 'on'      , ...
            'XColor'      , [.3 .3 .3], ...
            'YColor'      , [.3 .3 .3], ...
            'LineWidth'   , 1         , ...
            'FontName'   , 'Helvetica');
    subplot(2,4,6), plot(t(:),state(:,8),'k-o','MarkerIndices',1:ceil(length(t)/20):length(t)), ...
        hold on, plot(t(:),state(:,9),'k-^','MarkerIndices',1:ceil(length(t)/20):length(t)), ...
        plot(t(:),state(:,10),'k-s','MarkerIndices',1:ceil(length(t)/20):length(t)),hold off, ...
        title('Gas Accumulation'),...
        xlabel('Time [s]'),...
        ylabel('Mass [kg]');
        legend('Oxidizer','Fuel','Air');
        set(gca, ...
            'Box'         , 'off'     , ...
            'TickDir'     , 'out'     , ...
            'XMinorTick'  , 'on'      , ...
            'YMinorTick'  , 'on'      , ...
            'YGrid'       , 'on'      , ...
            'XColor'      , [.3 .3 .3], ...
            'YColor'      , [.3 .3 .3], ...
            'LineWidth'   , 1         , ...
            'FontName'   , 'Helvetica');
    subplot(2,4,7), plot(t(:),state(:,6),'k'), ...
        title('Average Chamber Temperature'),...
        xlabel('Time [s]'),...
        ylabel('Temperature [K]');
        set(gca, ...
            'Box'         , 'off'     , ...
            'TickDir'     , 'out'     , ...
            'XMinorTick'  , 'on'      , ...
            'YMinorTick'  , 'on'      , ...
            'YGrid'       , 'on'      , ...
            'XColor'      , [.3 .3 .3], ...
            'YColor'      , [.3 .3 .3], ...
            'LineWidth'   , 1         , ...
            'FontName'   , 'Helvetica');
    subplot(2,4,8), plot(t(2:end),F,'k'), ...
        title('Thrust'),...
        xlabel('Time [s]'),...
        ylabel('Thrust [N]');
        set(gca, ...
            'Box'         , 'off'     , ...
            'TickDir'     , 'out'     , ...
            'XMinorTick'  , 'on'      , ...
            'YMinorTick'  , 'on'      , ...
            'YGrid'       , 'on'      , ...
            'XColor'      , [.3 .3 .3], ...
            'YColor'      , [.3 .3 .3], ...
            'LineWidth'   , 1         , ...
            'FontName'   , 'Helvetica');
end
